In [1942]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2012]:
data1 = pd.read_excel("C:/Users/samba/OneDrive/Desktop/TAMU CORPUS/Driscoll/combined_yearly_datasets/2019_5.xlsx")
data1

day  average_cc_19_5  average_eg_19_5
0     0         0.000180        -0.015000
1    13         0.023000        -0.007000
2    25         1.880306        -0.006263
3    35        17.650586         0.030711
4    41        33.620998         0.063220
5    49        46.629007         0.090656
6    55        54.433813         0.107117
7    62        60.970851         0.132073
8    69        67.916843         0.148381
9    77        76.020499         0.167405
10   84        84.124156         0.186430
11   91        84.260000         0.177000
12   97        67.508885         0.138660
13  111        54.401694         0.102576
14  116        29.930000         0.062000

In [2013]:
in_seq1 = data1['average_cc_19_5'].to_numpy()
#in_seq2 = data1['average_ch_20_5'].to_numpy()
out_seq = data1['average_eg_19_5'].to_numpy()
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
#in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
dataset = np.hstack((in_seq1, out_seq))
print(dataset)

[[ 1.80000000e-04 -1.50000000e-02]
 [ 2.30000000e-02 -7.00000000e-03]
 [ 1.88030598e+00 -6.26265000e-03]
 [ 1.76505855e+01  3.07108240e-02]
 [ 3.36209981e+01  6.32200840e-02]
 [ 4.66290074e+01  9.06558130e-02]
 [ 5.44338130e+01  1.07117251e-01]
 [ 6.09708513e+01  1.32073492e-01]
 [ 6.79168427e+01  1.48380539e-01]
 [ 7.60204994e+01  1.67405428e-01]
 [ 8.41241561e+01  1.86430317e-01]
 [ 8.42600000e+01  1.77000000e-01]
 [ 6.75088851e+01  1.38659683e-01]
 [ 5.44016935e+01  1.02575956e-01]
 [ 2.99300000e+01  6.20000000e-02]]


In [2014]:
training_set = dataset[0:1]
testing_set = dataset[9:12]

In [2015]:
testing_set

array([[76.02049941,  0.16740543],
       [84.12415611,  0.18643032],
       [84.26      ,  0.177     ]])

In [2016]:
training_set

array([[ 1.80000000e-04, -1.50000000e-02],
       [ 2.30000000e-02, -7.00000000e-03],
       [ 1.88030598e+00, -6.26265000e-03],
       [ 1.76505855e+01,  3.07108240e-02],
       [ 3.36209981e+01,  6.32200840e-02],
       [ 4.66290074e+01,  9.06558130e-02],
       [ 5.44338130e+01,  1.07117251e-01],
       [ 6.09708513e+01,  1.32073492e-01],
       [ 6.79168427e+01,  1.48380539e-01],
       [ 7.60204994e+01,  1.67405428e-01],
       [ 8.41241561e+01,  1.86430317e-01],
       [ 8.42600000e+01,  1.77000000e-01]])

In [2017]:
# choose a number of time steps
n_steps = 3
# split into samples
X,y = list(), list()
for i in range(len(training_set)):
    #find the end of this pattern
    end_ix = i + n_steps
    #check if we are beyond the sequence
    if end_ix > len(training_set)-1:
        break
    #gather input and output parts of the pattern
    seq_x, seq_y = training_set[i:end_ix, :], training_set[end_ix, :]
    X.append(seq_x)
    y.append(seq_y)
X = np.array(X)
y = np.array(y)

In [2018]:
X

array([[[ 1.80000000e-04, -1.50000000e-02],
        [ 2.30000000e-02, -7.00000000e-03],
        [ 1.88030598e+00, -6.26265000e-03]],

       [[ 2.30000000e-02, -7.00000000e-03],
        [ 1.88030598e+00, -6.26265000e-03],
        [ 1.76505855e+01,  3.07108240e-02]],

       [[ 1.88030598e+00, -6.26265000e-03],
        [ 1.76505855e+01,  3.07108240e-02],
        [ 3.36209981e+01,  6.32200840e-02]],

       [[ 1.76505855e+01,  3.07108240e-02],
        [ 3.36209981e+01,  6.32200840e-02],
        [ 4.66290074e+01,  9.06558130e-02]],

       [[ 3.36209981e+01,  6.32200840e-02],
        [ 4.66290074e+01,  9.06558130e-02],
        [ 5.44338130e+01,  1.07117251e-01]],

       [[ 4.66290074e+01,  9.06558130e-02],
        [ 5.44338130e+01,  1.07117251e-01],
        [ 6.09708513e+01,  1.32073492e-01]],

       [[ 5.44338130e+01,  1.07117251e-01],
        [ 6.09708513e+01,  1.32073492e-01],
        [ 6.79168427e+01,  1.48380539e-01]],

       [[ 6.09708513e+01,  1.32073492e-01],
        [ 6.791684

In [2019]:
print(X.shape)

(9, 3, 2)


In [2020]:
y

array([[1.76505855e+01, 3.07108240e-02],
       [3.36209981e+01, 6.32200840e-02],
       [4.66290074e+01, 9.06558130e-02],
       [5.44338130e+01, 1.07117251e-01],
       [6.09708513e+01, 1.32073492e-01],
       [6.79168427e+01, 1.48380539e-01],
       [7.60204994e+01, 1.67405428e-01],
       [8.41241561e+01, 1.86430317e-01],
       [8.42600000e+01, 1.77000000e-01]])

In [2021]:
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import TimeDistributed
from tensorflow.keras.layers import Flatten

In [2022]:
# define model
n_features = X.shape[2]
model = Sequential()
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(100, activation='relu'))
model.add(Dense(n_features))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=400, verbose=0)
# demonstrate prediction
x_input = testing_set
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[85.39143   0.525814]]
