In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [45]:
data1 = pd.read_excel("C:/Users/samba/OneDrive/Desktop/TAMU CORPUS/Driscoll/combined_yearly_datasets/2021_0.xlsx")
data1

day  average_cc_21_0  average_ch_21_0  average_eg_21_0
0     0         0.002520         0.000000        -0.008555
1    13         0.473314         0.007585         0.005645
2    25        14.547168         0.031846         0.024015
3    35        21.776037         0.031630         0.062260
4    41        29.348252         0.066848         0.112673
5    49        46.459822         0.172606         0.184020
6    55        62.859898         0.248127         0.226193
7    62        76.352083         0.361994         0.304504
8    69        89.949687         0.452416         0.315696
9    77        97.915300         0.662580         0.283232
10   84        98.198073         0.677824         0.286647
11   91        99.354463         0.704850         0.287615
12   97        99.480517         0.759954         0.278510
13  111        99.615371         0.781171         0.261826
14  116        99.599741         0.789335         0.260186

In [46]:
in_seq1 = data1['average_cc_21_0'].to_numpy()
in_seq2 = data1['average_ch_21_0'].to_numpy()
out_seq = data1['average_eg_21_0'].to_numpy()
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
dataset = np.hstack((in_seq1, in_seq2, out_seq))
print(dataset)

[[ 2.52013300e-03  0.00000000e+00 -8.55505600e-03]
 [ 4.73313898e-01  7.58539000e-03  5.64517400e-03]
 [ 1.45471678e+01  3.18457080e-02  2.40152370e-02]
 [ 2.17760368e+01  3.16303710e-02  6.22599040e-02]
 [ 2.93482519e+01  6.68479670e-02  1.12672784e-01]
 [ 4.64598223e+01  1.72605752e-01  1.84020140e-01]
 [ 6.28598980e+01  2.48127261e-01  2.26192788e-01]
 [ 7.63520827e+01  3.61993876e-01  3.04503516e-01]
 [ 8.99496872e+01  4.52416127e-01  3.15695890e-01]
 [ 9.79153002e+01  6.62580354e-01  2.83232061e-01]
 [ 9.81980727e+01  6.77823872e-01  2.86646867e-01]
 [ 9.93544632e+01  7.04849784e-01  2.87614739e-01]
 [ 9.94805171e+01  7.59954378e-01  2.78510041e-01]
 [ 9.96153710e+01  7.81171304e-01  2.61825936e-01]
 [ 9.95997411e+01  7.89334823e-01  2.60185792e-01]]


In [47]:
training_set = dataset[0:8]
testing_set = dataset[5:8]

In [48]:
testing_set

array([[46.45982227,  0.17260575,  0.18402014],
       [62.85989802,  0.24812726,  0.22619279],
       [76.35208271,  0.36199388,  0.30450352]])

In [49]:
training_set

array([[ 2.52013300e-03,  0.00000000e+00, -8.55505600e-03],
       [ 4.73313898e-01,  7.58539000e-03,  5.64517400e-03],
       [ 1.45471678e+01,  3.18457080e-02,  2.40152370e-02],
       [ 2.17760368e+01,  3.16303710e-02,  6.22599040e-02],
       [ 2.93482519e+01,  6.68479670e-02,  1.12672784e-01],
       [ 4.64598223e+01,  1.72605752e-01,  1.84020140e-01],
       [ 6.28598980e+01,  2.48127261e-01,  2.26192788e-01],
       [ 7.63520827e+01,  3.61993876e-01,  3.04503516e-01]])

In [50]:
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# split into samples
X,y = list(), list()
for i in range(len(training_set)):
    #find the end of this pattern
    end_ix = i + n_steps_in
    out_end_ix = end_ix + n_steps_out
    #check if we are beyond the sequence
    if out_end_ix > len(training_set):
        break
    #gather input and output parts of the pattern
    seq_x, seq_y = training_set[i:end_ix, :], training_set[end_ix:out_end_ix, :]
    X.append(seq_x)
    y.append(seq_y)
X = np.array(X)
y = np.array(y)

In [51]:
X

array([[[ 2.52013300e-03,  0.00000000e+00, -8.55505600e-03],
        [ 4.73313898e-01,  7.58539000e-03,  5.64517400e-03],
        [ 1.45471678e+01,  3.18457080e-02,  2.40152370e-02]],

       [[ 4.73313898e-01,  7.58539000e-03,  5.64517400e-03],
        [ 1.45471678e+01,  3.18457080e-02,  2.40152370e-02],
        [ 2.17760368e+01,  3.16303710e-02,  6.22599040e-02]],

       [[ 1.45471678e+01,  3.18457080e-02,  2.40152370e-02],
        [ 2.17760368e+01,  3.16303710e-02,  6.22599040e-02],
        [ 2.93482519e+01,  6.68479670e-02,  1.12672784e-01]],

       [[ 2.17760368e+01,  3.16303710e-02,  6.22599040e-02],
        [ 2.93482519e+01,  6.68479670e-02,  1.12672784e-01],
        [ 4.64598223e+01,  1.72605752e-01,  1.84020140e-01]]])

In [52]:
print(X.shape)

(4, 3, 3)


In [53]:
y

array([[[2.17760368e+01, 3.16303710e-02, 6.22599040e-02],
        [2.93482519e+01, 6.68479670e-02, 1.12672784e-01]],

       [[2.93482519e+01, 6.68479670e-02, 1.12672784e-01],
        [4.64598223e+01, 1.72605752e-01, 1.84020140e-01]],

       [[4.64598223e+01, 1.72605752e-01, 1.84020140e-01],
        [6.28598980e+01, 2.48127261e-01, 2.26192788e-01]],

       [[6.28598980e+01, 2.48127261e-01, 2.26192788e-01],
        [7.63520827e+01, 3.61993876e-01, 3.04503516e-01]]])

In [54]:
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import TimeDistributed
from tensorflow.keras.layers import Flatten
from keras.layers import RepeatVector

In [55]:
n_features = X.shape[2]
# define model
model = Sequential()
model.add(LSTM(200, activation='relu', input_shape=(n_steps_in, n_features)))
model.add(RepeatVector(n_steps_out))
model.add(LSTM(200, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(n_features)))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=100, verbose=0)
# demonstrate prediction
x_input = testing_set
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[[ 1.0130218e+02 -7.8330445e-01  3.0549711e-02]
  [ 1.2430914e+02  1.4982021e+00  1.2341392e+00]]]
