In [1155]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [1156]:
data1 = pd.read_csv("C:/Users/samba/OneDrive/Desktop/TAMU CORPUS/Driscoll/2021/kmeans/class_5.csv")
data1

FID     0cc21    13cc21    25cc21     35cc21     41cc21     49cc21  \
0      30  0.007352  0.000000  2.218564   4.602347   6.627193  13.972676   
1      31  0.491373  0.003063  0.821826   1.306331   2.111537   4.586754   
2      32  0.073522  0.032472  0.067840   0.139003   0.489570   1.465699   
3      33  0.162362  0.000000  0.073769   0.235330   0.689170   1.166007   
4      34  1.224145  0.012254  0.123762   0.237769   0.918932  16.550389   
..    ...       ...       ...       ...        ...        ...        ...   
288  3640  0.000000  0.030634  1.149004   1.718071   4.153635   9.137019   
289  3643  0.000000  0.000000  0.872143   2.131606   6.934309  19.889466   
290  3644  0.000000  0.000613  0.218259   0.830749   2.199720   9.070834   
291  3645  0.000000  0.000000  0.458467   0.866331   3.870142  10.140989   
292  3663  0.000000  0.099868  8.757202  15.587258  25.977138  47.122595   

        55cc21     62cc21     69cc21  ...    77eg21    84eg21    91eg21  \
0    20.546999  26.413682  39.406798  ...  0.125951  0.133590  0.145648   
1     7.334857   9.270808  17.535132  ...  0.061718  0.057969  0.078309   
2     2.666544   3.820457   7.529642  ...  0.030983  0.021924  0.036464   
3     1.857034   2.066418   4.165219  ...  0.016579  0.020474  0.041077   
4    47.723995  31.915677  35.917086  ...  0.053834  0.036394  0.033602   
..         ...        ...        ...  ...       ...       ...       ...   
288  15.240191  21.063816  30.326977  ...  0.091648  0.097202  0.134164   
289  24.640354  34.089551  43.553355  ...  0.114550  0.121770  0.155080   
290  14.882044  21.268465  30.521330  ...  0.091467  0.088761  0.113343   
291  11.890870  17.860053  27.083067  ...  0.081848  0.080026  0.113552   
292  59.290352  65.339362  69.538180  ...  0.132662  0.156102  0.179545   

       97eg21   106eg21   111eg21   116eg21   124eg21  yield  labels  
0    0.156908  0.164927  0.168662  0.195338  0.032894  45.07       5  
1    0.107683  0.136193  0.156333  0.193968  0.066459  23.29       5  
2    0.049911  0.070725  0.084951  0.121534  0.047936   6.83       5  
3    0.066422  0.088152  0.092934  0.122996  0.047356  19.31       5  
4    0.055498  0.058579  0.061343  0.137633  0.091573  12.26       5  
..        ...       ...       ...       ...       ...    ...     ...  
288  0.144348  0.161992  0.191958  0.159145  0.021552  31.78       5  
289  0.156113  0.149990  0.144570  0.135929  0.020036  35.64       5  
290  0.132919  0.149260  0.155461  0.180157  0.012629  23.64       5  
291  0.139911  0.178092  0.194683  0.221344  0.021966  22.64       5  
292  0.188666  0.121494  0.107424  0.145347  0.007608  15.39       5  

[293 rows x 54 columns]

In [1157]:
data1 = data1.drop('labels',axis=1)
data1

FID     0cc21    13cc21    25cc21     35cc21     41cc21     49cc21  \
0      30  0.007352  0.000000  2.218564   4.602347   6.627193  13.972676   
1      31  0.491373  0.003063  0.821826   1.306331   2.111537   4.586754   
2      32  0.073522  0.032472  0.067840   0.139003   0.489570   1.465699   
3      33  0.162362  0.000000  0.073769   0.235330   0.689170   1.166007   
4      34  1.224145  0.012254  0.123762   0.237769   0.918932  16.550389   
..    ...       ...       ...       ...        ...        ...        ...   
288  3640  0.000000  0.030634  1.149004   1.718071   4.153635   9.137019   
289  3643  0.000000  0.000000  0.872143   2.131606   6.934309  19.889466   
290  3644  0.000000  0.000613  0.218259   0.830749   2.199720   9.070834   
291  3645  0.000000  0.000000  0.458467   0.866331   3.870142  10.140989   
292  3663  0.000000  0.099868  8.757202  15.587258  25.977138  47.122595   

        55cc21     62cc21     69cc21  ...    69eg21    77eg21    84eg21  \
0    20.546999  26.413682  39.406798  ...  0.138207  0.125951  0.133590   
1     7.334857   9.270808  17.535132  ...  0.070538  0.061718  0.057969   
2     2.666544   3.820457   7.529642  ...  0.039325  0.030983  0.021924   
3     1.857034   2.066418   4.165219  ...  0.019774  0.016579  0.020474   
4    47.723995  31.915677  35.917086  ...  0.118045  0.053834  0.036394   
..         ...        ...        ...  ...       ...       ...       ...   
288  15.240191  21.063816  30.326977  ...  0.086228  0.091648  0.097202   
289  24.640354  34.089551  43.553355  ...  0.123552  0.114550  0.121770   
290  14.882044  21.268465  30.521330  ...  0.085367  0.091467  0.088761   
291  11.890870  17.860053  27.083067  ...  0.077457  0.081848  0.080026   
292  59.290352  65.339362  69.538180  ...  0.131715  0.132662  0.156102   

       91eg21    97eg21   106eg21   111eg21   116eg21   124eg21  yield  
0    0.145648  0.156908  0.164927  0.168662  0.195338  0.032894  45.07  
1    0.078309  0.107683  0.136193  0.156333  0.193968  0.066459  23.29  
2    0.036464  0.049911  0.070725  0.084951  0.121534  0.047936   6.83  
3    0.041077  0.066422  0.088152  0.092934  0.122996  0.047356  19.31  
4    0.033602  0.055498  0.058579  0.061343  0.137633  0.091573  12.26  
..        ...       ...       ...       ...       ...       ...    ...  
288  0.134164  0.144348  0.161992  0.191958  0.159145  0.021552  31.78  
289  0.155080  0.156113  0.149990  0.144570  0.135929  0.020036  35.64  
290  0.113343  0.132919  0.149260  0.155461  0.180157  0.012629  23.64  
291  0.113552  0.139911  0.178092  0.194683  0.221344  0.021966  22.64  
292  0.179545  0.188666  0.121494  0.107424  0.145347  0.007608  15.39  

[293 rows x 53 columns]

In [1158]:
data1 = data1.T

In [1159]:
data1 = data1.iloc[1:,:]
data1

0          1          2          3          4          5    \
0cc21     0.007352   0.491373   0.073522   0.162362   1.224145   0.092515   
13cc21    0.000000   0.003063   0.032472   0.000000   0.012254   0.209538   
25cc21    2.218564   0.821826   0.067840   0.073769   0.123762   0.400929   
35cc21    4.602347   1.306331   0.139003   0.235330   0.237769   0.244475   
41cc21    6.627193   2.111537   0.489570   0.689170   0.918932   0.665937   
49cc21   13.972676   4.586754   1.465699   1.166007  16.550389   3.256570   
55cc21   20.546999   7.334857   2.666544   1.857034  47.723995   5.031982   
62cc21   26.413682   9.270808   3.820457   2.066418  31.915677   6.978250   
69cc21   39.406798  17.535132   7.529642   4.165219  35.917086  11.765065   
77cc21   56.546090  31.759205  24.010750  14.047837  53.440473  18.297232   
84cc21   57.480247  30.613951  17.739317  11.436711  23.407265  20.681537   
91cc21   62.667952  31.415211  15.115183  13.113679   9.509272  24.976505   
97cc21   66.433754  37.885515  19.176042  20.184897  11.595414  29.069967   
111cc21  73.002432  49.086738  25.099550  31.706631  19.861279  36.905968   
116cc21  77.666091  58.990594  32.080457  38.854071  22.131685  42.100949   
121cc21  71.812576  60.204943  35.722169  37.814881  24.003419  38.337024   
124cc21  77.668369  75.167720  55.092752  52.352407  71.943170  46.910708   
0ch21     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
13ch21    0.003867   0.003751   0.004529   0.004088   0.004321   0.051617   
25ch21    0.008647   0.007216   0.006502   0.007537   0.009586   0.019100   
35ch21    0.005170   0.004972   0.004370   0.004756   0.005778   0.023075   
41ch21    0.012352   0.013929   0.013013   0.024821   0.023550   0.018130   
49ch21    0.091404   0.050667   0.007477   0.014950   0.023609   0.029384   
55ch21    0.154210   0.113264   0.027985   0.023569   0.019124   0.196278   
62ch21    0.218535   0.175442   0.031061   0.074914   0.126348   0.107717   
69ch21    0.268273   0.222654   0.113562   0.116622   0.187808   0.193755   
77ch21    0.244224   0.204305   0.082821   0.074736   0.329250   0.099674   
84ch21    0.229216   0.213884   0.045988   0.084068   0.282697   0.078327   
91ch21    0.302410   0.268799   0.120622   0.101071   0.158061   0.136659   
97ch21    0.377899   0.351720   0.189732   0.158796   0.216752   0.203405   
106ch21   0.380758   0.334672   0.216804   0.194567   0.261466   0.239933   
111ch21   0.453715   0.411256   0.318137   0.343844   0.451279   0.313632   
116ch21   0.376291   0.381766   0.295900   0.295764   0.371585   0.259629   
124ch21   0.448916   0.477230   0.379418   0.345477   0.188754   0.311048   
0eg21    -0.009223  -0.009480  -0.014338  -0.019320  -0.006268  -0.007126   
13eg21   -0.012479  -0.013097  -0.020128  -0.019525  -0.015423  -0.010119   
25eg21    0.000898  -0.005670  -0.005601  -0.005686  -0.002013  -0.004797   
35eg21    0.005311  -0.004000  -0.005358   0.007831   0.002070  -0.003905   
41eg21    0.015066  -0.005264  -0.011804  -0.007433   0.019189  -0.003028   
49eg21    0.039372   0.009280  -0.003156  -0.002268   0.069922   0.001907   
55eg21    0.057240   0.017469   0.003763  -0.001848   0.074321   0.009041   
62eg21    0.109436   0.044049   0.014211   0.007903   0.097682   0.022772   
69eg21    0.138207   0.070538   0.039325   0.019774   0.118045   0.034542   
77eg21    0.125951   0.061718   0.030983   0.016579   0.053834   0.033118   
84eg21    0.133590   0.057969   0.021924   0.020474   0.036394   0.039956   
91eg21    0.145648   0.078309   0.036464   0.041077   0.033602   0.051135   
97eg21    0.156908   0.107683   0.049911   0.066422   0.055498   0.071066   
106eg21   0.164927   0.136193   0.070725   0.088152   0.058579   0.078018   
111eg21   0.168662   0.156333   0.084951   0.092934   0.061343   0.080854   
116eg21   0.195338   0.193968   0.121534   0.122996   0.137633   0.097290   
124eg21   0.032894   0.066459   0.047936   0.047356   0.091573   0.026296   
yield    45

In [1160]:
data1['average'] = data1.iloc[:,:].mean(axis=1)

In [1161]:
data1

0          1          2          3          4          5  \
0cc21     0.007352   0.491373   0.073522   0.162362   1.224145   0.092515   
13cc21    0.000000   0.003063   0.032472   0.000000   0.012254   0.209538   
25cc21    2.218564   0.821826   0.067840   0.073769   0.123762   0.400929   
35cc21    4.602347   1.306331   0.139003   0.235330   0.237769   0.244475   
41cc21    6.627193   2.111537   0.489570   0.689170   0.918932   0.665937   
49cc21   13.972676   4.586754   1.465699   1.166007  16.550389   3.256570   
55cc21   20.546999   7.334857   2.666544   1.857034  47.723995   5.031982   
62cc21   26.413682   9.270808   3.820457   2.066418  31.915677   6.978250   
69cc21   39.406798  17.535132   7.529642   4.165219  35.917086  11.765065   
77cc21   56.546090  31.759205  24.010750  14.047837  53.440473  18.297232   
84cc21   57.480247  30.613951  17.739317  11.436711  23.407265  20.681537   
91cc21   62.667952  31.415211  15.115183  13.113679   9.509272  24.976505   
97cc21   66.433754  37.885515  19.176042  20.184897  11.595414  29.069967   
111cc21  73.002432  49.086738  25.099550  31.706631  19.861279  36.905968   
116cc21  77.666091  58.990594  32.080457  38.854071  22.131685  42.100949   
121cc21  71.812576  60.204943  35.722169  37.814881  24.003419  38.337024   
124cc21  77.668369  75.167720  55.092752  52.352407  71.943170  46.910708   
0ch21     0.000000   0.000000   0.000000   0.000000   0.000000   0.000000   
13ch21    0.003867   0.003751   0.004529   0.004088   0.004321   0.051617   
25ch21    0.008647   0.007216   0.006502   0.007537   0.009586   0.019100   
35ch21    0.005170   0.004972   0.004370   0.004756   0.005778   0.023075   
41ch21    0.012352   0.013929   0.013013   0.024821   0.023550   0.018130   
49ch21    0.091404   0.050667   0.007477   0.014950   0.023609   0.029384   
55ch21    0.154210   0.113264   0.027985   0.023569   0.019124   0.196278   
62ch21    0.218535   0.175442   0.031061   0.074914   0.126348   0.107717   
69ch21    0.268273   0.222654   0.113562   0.116622   0.187808   0.193755   
77ch21    0.244224   0.204305   0.082821   0.074736   0.329250   0.099674   
84ch21    0.229216   0.213884   0.045988   0.084068   0.282697   0.078327   
91ch21    0.302410   0.268799   0.120622   0.101071   0.158061   0.136659   
97ch21    0.377899   0.351720   0.189732   0.158796   0.216752   0.203405   
106ch21   0.380758   0.334672   0.216804   0.194567   0.261466   0.239933   
111ch21   0.453715   0.411256   0.318137   0.343844   0.451279   0.313632   
116ch21   0.376291   0.381766   0.295900   0.295764   0.371585   0.259629   
124ch21   0.448916   0.477230   0.379418   0.345477   0.188754   0.311048   
0eg21    -0.009223  -0.009480  -0.014338  -0.019320  -0.006268  -0.007126   
13eg21   -0.012479  -0.013097  -0.020128  -0.019525  -0.015423  -0.010119   
25eg21    0.000898  -0.005670  -0.005601  -0.005686  -0.002013  -0.004797   
35eg21    0.005311  -0.004000  -0.005358   0.007831   0.002070  -0.003905   
41eg21    0.015066  -0.005264  -0.011804  -0.007433   0.019189  -0.003028   
49eg21    0.039372   0.009280  -0.003156  -0.002268   0.069922   0.001907   
55eg21    0.057240   0.017469   0.003763  -0.001848   0.074321   0.009041   
62eg21    0.109436   0.044049   0.014211   0.007903   0.097682   0.022772   
69eg21    0.138207   0.070538   0.039325   0.019774   0.118045   0.034542   
77eg21    0.125951   0.061718   0.030983   0.016579   0.053834   0.033118   
84eg21    0.133590   0.057969   0.021924   0.020474   0.036394   0.039956   
91eg21    0.145648   0.078309   0.036464   0.041077   0.033602   0.051135   
97eg21    0.156908   0.107683   0.049911   0.066422   0.055498   0.071066   
106eg21   0.164927   0.136193   0.070725   0.088152   0.058579   0.078018   
111eg21   0.168662   0.156333   0.084951   0.092934   0.061343   0.080854   
116eg21   0.195338   0.193968   0.121534   0.122996   0.137633   0.097290   
124eg21   0.032894   0.066459   0.047936   0.047356   0.091573   0.026296   
yield    45.0

In [1162]:
data1 = data1[34:51]

In [1163]:
data1

0         1         2         3         4         5         6  \
0eg21   -0.009223 -0.009480 -0.014338 -0.019320 -0.006268 -0.007126 -0.014152   
13eg21  -0.012479 -0.013097 -0.020128 -0.019525 -0.015423 -0.010119 -0.014826   
25eg21   0.000898 -0.005670 -0.005601 -0.005686 -0.002013 -0.004797 -0.003075   
35eg21   0.005311 -0.004000 -0.005358  0.007831  0.002070 -0.003905  0.000052   
41eg21   0.015066 -0.005264 -0.011804 -0.007433  0.019189 -0.003028 -0.009024   
49eg21   0.039372  0.009280 -0.003156 -0.002268  0.069922  0.001907  0.000216   
55eg21   0.057240  0.017469  0.003763 -0.001848  0.074321  0.009041  0.010141   
62eg21   0.109436  0.044049  0.014211  0.007903  0.097682  0.022772  0.022214   
69eg21   0.138207  0.070538  0.039325  0.019774  0.118045  0.034542  0.035263   
77eg21   0.125951  0.061718  0.030983  0.016579  0.053834  0.033118  0.036956   
84eg21   0.133590  0.057969  0.021924  0.020474  0.036394  0.039956  0.037443   
91eg21   0.145648  0.078309  0.036464  0.041077  0.033602  0.051135  0.061366   
97eg21   0.156908  0.107683  0.049911  0.066422  0.055498  0.071066  0.083346   
106eg21  0.164927  0.136193  0.070725  0.088152  0.058579  0.078018  0.102341   
111eg21  0.168662  0.156333  0.084951  0.092934  0.061343  0.080854  0.126761   
116eg21  0.195338  0.193968  0.121534  0.122996  0.137633  0.097290  0.149177   
124eg21  0.032894  0.066459  0.047936  0.047356  0.091573  0.026296  0.045049   

                7         8         9  ...       284       285       286  \
0eg21   -0.016583 -0.019709 -0.006803  ... -0.014543 -0.019770 -0.024042   
13eg21  -0.017679 -0.017760 -0.010755  ... -0.011508 -0.016141 -0.011622   
25eg21  -0.001520  0.000552  0.005026  ... -0.005441 -0.009657 -0.013374   
35eg21  -0.003948 -0.001845  0.008185  ... -0.000817 -0.004074 -0.006951   
41eg21  -0.006156  0.006392  0.035074  ...  0.002932  0.004688  0.002188   
49eg21   0.002490  0.025853  0.088012  ...  0.024014  0.023254  0.017508   
55eg21   0.020351  0.041872  0.088329  ...  0.045520  0.052228  0.049095   
62eg21   0.042985  0.081738  0.151362  ...  0.076703  0.095296  0.097483   
69eg21   0.063865  0.115062  0.166511  ...  0.090661  0.104188  0.107339   
77eg21   0.059808  0.100605  0.106429  ...  0.086590  0.098850  0.114128   
84eg21   0.080887  0.124206  0.120035  ...  0.083361  0.102860  0.110575   
91eg21   0.104035  0.152857  0.134735  ...  0.100288  0.117096  0.127106   
97eg21   0.139473  0.188334  0.152398  ...  0.114759  0.146940  0.163897   
106eg21  0.166497  0.209934  0.143202  ...  0.127544  0.165984  0.179913   
111eg21  0.190758  0.222064  0.145958  ...  0.135856  0.170546  0.184275   
116eg21  0.212706  0.222653  0.177702  ...  0.169345  0.198856  0.231307   
124eg21  0.056552  0.056456  0.085791  ...  0.023186  0.027915  0.022534   

              287       288       289       290       291       292   average  
0eg21   -0.015346 -0.021535 -0.022427 -0.012251 -0.019858 -0.010947 -0.012219  
13eg21  -0.004891 -0.010111 -0.009411 -0.009821 -0.010258  0.002332 -0.009398  
25eg21   0.004073 -0.006725 -0.006055 -0.002179 -0.009053  0.013091 -0.000984  
35eg21   0.049067  0.004596  0.009353  0.002277 -0.000791  0.060139  0.038073  
41eg21   0.067329  0.005232  0.027319  0.005571  0.009009  0.086771  0.048914  
49eg21   0.105761  0.027927  0.050334  0.027679  0.013156  0.128251  0.088629  
55eg21   0.136824  0.050016  0.057944  0.043631  0.039171  0.160933  0.103809  
62eg21   0.141487  0.084118  0.108879  0.076527  0.067697  0.186912  0.125105  
69eg21   0.082140  0.086228  0.123552  0.085367  0.077457  0.131715  0.099340  
77eg21   0.096591  0.091648  0.114550  0.091467  0.081848  0.132662  0.085825  
84eg21   0.120473  0.097202  0.121770  0.088761  0.080026  0.156102  0.103171  
91eg21   0.150990  0.134164  0.155080  0.113343  0.113552  0.179545  0.121509  
97eg21   0.190419  0.144348  0.156113  0.132919  0.139911  0.188666  0.118740  
106eg21  0.120562  0.161992  0.149990  0.149260  0.178092  0.121494 

In [1164]:
data1['average_eg'] = data1['average']

C:\Users\samba\AppData\Local\Temp\ipykernel_9888\2134930401.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['average_eg'] = data1['average']


In [1165]:
data1

0         1         2         3         4         5         6  \
0eg21   -0.009223 -0.009480 -0.014338 -0.019320 -0.006268 -0.007126 -0.014152   
13eg21  -0.012479 -0.013097 -0.020128 -0.019525 -0.015423 -0.010119 -0.014826   
25eg21   0.000898 -0.005670 -0.005601 -0.005686 -0.002013 -0.004797 -0.003075   
35eg21   0.005311 -0.004000 -0.005358  0.007831  0.002070 -0.003905  0.000052   
41eg21   0.015066 -0.005264 -0.011804 -0.007433  0.019189 -0.003028 -0.009024   
49eg21   0.039372  0.009280 -0.003156 -0.002268  0.069922  0.001907  0.000216   
55eg21   0.057240  0.017469  0.003763 -0.001848  0.074321  0.009041  0.010141   
62eg21   0.109436  0.044049  0.014211  0.007903  0.097682  0.022772  0.022214   
69eg21   0.138207  0.070538  0.039325  0.019774  0.118045  0.034542  0.035263   
77eg21   0.125951  0.061718  0.030983  0.016579  0.053834  0.033118  0.036956   
84eg21   0.133590  0.057969  0.021924  0.020474  0.036394  0.039956  0.037443   
91eg21   0.145648  0.078309  0.036464  0.041077  0.033602  0.051135  0.061366   
97eg21   0.156908  0.107683  0.049911  0.066422  0.055498  0.071066  0.083346   
106eg21  0.164927  0.136193  0.070725  0.088152  0.058579  0.078018  0.102341   
111eg21  0.168662  0.156333  0.084951  0.092934  0.061343  0.080854  0.126761   
116eg21  0.195338  0.193968  0.121534  0.122996  0.137633  0.097290  0.149177   
124eg21  0.032894  0.066459  0.047936  0.047356  0.091573  0.026296  0.045049   

                7         8         9  ...       285       286       287  \
0eg21   -0.016583 -0.019709 -0.006803  ... -0.019770 -0.024042 -0.015346   
13eg21  -0.017679 -0.017760 -0.010755  ... -0.016141 -0.011622 -0.004891   
25eg21  -0.001520  0.000552  0.005026  ... -0.009657 -0.013374  0.004073   
35eg21  -0.003948 -0.001845  0.008185  ... -0.004074 -0.006951  0.049067   
41eg21  -0.006156  0.006392  0.035074  ...  0.004688  0.002188  0.067329   
49eg21   0.002490  0.025853  0.088012  ...  0.023254  0.017508  0.105761   
55eg21   0.020351  0.041872  0.088329  ...  0.052228  0.049095  0.136824   
62eg21   0.042985  0.081738  0.151362  ...  0.095296  0.097483  0.141487   
69eg21   0.063865  0.115062  0.166511  ...  0.104188  0.107339  0.082140   
77eg21   0.059808  0.100605  0.106429  ...  0.098850  0.114128  0.096591   
84eg21   0.080887  0.124206  0.120035  ...  0.102860  0.110575  0.120473   
91eg21   0.104035  0.152857  0.134735  ...  0.117096  0.127106  0.150990   
97eg21   0.139473  0.188334  0.152398  ...  0.146940  0.163897  0.190419   
106eg21  0.166497  0.209934  0.143202  ...  0.165984  0.179913  0.120562   
111eg21  0.190758  0.222064  0.145958  ...  0.170546  0.184275  0.124228   
116eg21  0.212706  0.222653  0.177702  ...  0.198856  0.231307  0.173587   
124eg21  0.056552  0.056456  0.085791  ...  0.027915  0.022534  0.014502   

              288       289       290       291       292   average  \
0eg21   -0.021535 -0.022427 -0.012251 -0.019858 -0.010947 -0.012219   
13eg21  -0.010111 -0.009411 -0.009821 -0.010258  0.002332 -0.009398   
25eg21  -0.006725 -0.006055 -0.002179 -0.009053  0.013091 -0.000984   
35eg21   0.004596  0.009353  0.002277 -0.000791  0.060139  0.038073   
41eg21   0.005232  0.027319  0.005571  0.009009  0.086771  0.048914   
49eg21   0.027927  0.050334  0.027679  0.013156  0.128251  0.088629   
55eg21   0.050016  0.057944  0.043631  0.039171  0.160933  0.103809   
62eg21   0.084118  0.108879  0.076527  0.067697  0.186912  0.125105   
69eg21   0.086228  0.123552  0.085367  0.077457  0.131715  0.099340   
77eg21   0.091648  0.114550  0.091467  0.081848  0.132662  0.085825   
84eg21   0.097202  0.121770  0.088761  0.080026  0.156102  0.103171   
91eg21   0.134164  0.155080  0.113343  0.113552  0.179545  0.121509   
97eg21   0.144348  0.156113  0.132919  0.139911  0.188666  0.118740   
106eg21  0.161992  0.149990  0.149260  0.178092  0.121494  0.153823   
111eg21  0.191958  0.144570  0.155461  0.194683  0.107424  0.147955   
116eg21  0.159145  0.135929  0.180157  0.221344  0.1

In [1166]:
data2 = data1['average_eg']

In [1167]:
data2

0eg21     -0.012219
13eg21    -0.009398
25eg21    -0.000984
35eg21     0.038073
41eg21     0.048914
49eg21     0.088629
55eg21     0.103809
62eg21     0.125105
69eg21     0.099340
77eg21     0.085825
84eg21     0.103171
91eg21     0.121509
97eg21     0.118740
106eg21    0.153823
111eg21    0.147955
116eg21    0.183947
124eg21    0.021905
Name: average_eg, dtype: float64

In [1168]:
data2 = pd.DataFrame(data2)

In [1169]:
data2

average_eg
0eg21     -0.012219
13eg21    -0.009398
25eg21    -0.000984
35eg21     0.038073
41eg21     0.048914
49eg21     0.088629
55eg21     0.103809
62eg21     0.125105
69eg21     0.099340
77eg21     0.085825
84eg21     0.103171
91eg21     0.121509
97eg21     0.118740
106eg21    0.153823
111eg21    0.147955
116eg21    0.183947
124eg21    0.021905

In [1170]:
dataset_train = data2[0:13]
dataset_test = data2[13:16]

In [1171]:
training_set = data2.iloc[0:13,:].values
training_set

array([[-0.01221877],
       [-0.00939767],
       [-0.00098399],
       [ 0.03807291],
       [ 0.04891406],
       [ 0.0886287 ],
       [ 0.10380903],
       [ 0.1251049 ],
       [ 0.09934011],
       [ 0.08582541],
       [ 0.10317119],
       [ 0.12150924],
       [ 0.1187402 ]])

In [1172]:
#vanilla lstm
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional
from keras.layers import TimeDistributed
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import Flatten
# choose a number of time steps
n_steps = 3
# split into samples
X,y = list(), list()
for i in range(len(training_set)):
    #find the end of this pattern
    end_ix = i + n_steps
    #check if we are beyond the sequence
    if end_ix > len(training_set) - 1:
        break
    #gather input and output parts of the pattern
    seq_x, seq_y = training_set[i:end_ix], training_set[end_ix]
    X.append(seq_x)
    y.append(seq_y)
X = np.array(X)
y = np.array(y)
print (X)

[[[-0.01221877]
  [-0.00939767]
  [-0.00098399]]

 [[-0.00939767]
  [-0.00098399]
  [ 0.03807291]]

 [[-0.00098399]
  [ 0.03807291]
  [ 0.04891406]]

 [[ 0.03807291]
  [ 0.04891406]
  [ 0.0886287 ]]

 [[ 0.04891406]
  [ 0.0886287 ]
  [ 0.10380903]]

 [[ 0.0886287 ]
  [ 0.10380903]
  [ 0.1251049 ]]

 [[ 0.10380903]
  [ 0.1251049 ]
  [ 0.09934011]]

 [[ 0.1251049 ]
  [ 0.09934011]
  [ 0.08582541]]

 [[ 0.09934011]
  [ 0.08582541]
  [ 0.10317119]]

 [[ 0.08582541]
  [ 0.10317119]
  [ 0.12150924]]]


In [1176]:
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = data2.iloc[13:16,:].values
x_input = x_input.reshape((1, 3, 1))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[0.13702603]]


In [1177]:
#stacked LSTM
# univariate lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional
from keras.layers import TimeDistributed
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import Flatten
# choose a number of time steps
n_steps = 3
# split into samples
X,y = list(), list()
for i in range(len(training_set)):
    #find the end of this pattern
    end_ix = i + n_steps
    #check if we are beyond the sequence
    if end_ix > len(training_set) - 1:
        break
    #gather input and output parts of the pattern
    seq_x, seq_y = training_set[i:end_ix], training_set[end_ix]
    X.append(seq_x)
    y.append(seq_y)
X = np.array(X)
y = np.array(y)
print (X)

[[[-0.01221877]
  [-0.00939767]
  [-0.00098399]]

 [[-0.00939767]
  [-0.00098399]
  [ 0.03807291]]

 [[-0.00098399]
  [ 0.03807291]
  [ 0.04891406]]

 [[ 0.03807291]
  [ 0.04891406]
  [ 0.0886287 ]]

 [[ 0.04891406]
  [ 0.0886287 ]
  [ 0.10380903]]

 [[ 0.0886287 ]
  [ 0.10380903]
  [ 0.1251049 ]]

 [[ 0.10380903]
  [ 0.1251049 ]
  [ 0.09934011]]

 [[ 0.1251049 ]
  [ 0.09934011]
  [ 0.08582541]]

 [[ 0.09934011]
  [ 0.08582541]
  [ 0.10317119]]

 [[ 0.08582541]
  [ 0.10317119]
  [ 0.12150924]]]


In [1181]:
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(3, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = data2.iloc[13:16,:].values
x_input = x_input.reshape((1, 3, 1))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[0.13017339]]


In [1185]:
#Bidirectional LSTM
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional
# choose a number of time steps
n_steps = 3
# split into samples
X,y = list(), list()
for i in range(len(training_set)):
    #find the end of this pattern
    end_ix = i + n_steps
    #check if we are beyond the sequence
    if end_ix > len(training_set) - 1:
        break
    #gather input and output parts of the pattern
    seq_x, seq_y = training_set[i:end_ix], training_set[end_ix]
    X.append(seq_x)
    y.append(seq_y)
X = np.array(X)
y = np.array(y)
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = data2.iloc[13:16,:].values
x_input = x_input.reshape((1, 3, 1))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[0.13755155]]


In [1186]:
# univariate cnn lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional
from keras.layers import TimeDistributed
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import Flatten
# choose a number of time steps
n_steps = 4
# split into samples
X,y = list(), list()
for i in range(len(training_set)):
    #find the end of this pattern
    end_ix = i + n_steps
    #check if we are beyond the sequence
    if end_ix > len(training_set) - 1:
        break
    #gather input and output parts of the pattern
    seq_x, seq_y = training_set[i:end_ix], training_set[end_ix]
    X.append(seq_x)
    y.append(seq_y)
X = np.array(X)
y = np.array(y)
print (X)

[[[-0.01221877]
  [-0.00939767]
  [-0.00098399]
  [ 0.03807291]]

 [[-0.00939767]
  [-0.00098399]
  [ 0.03807291]
  [ 0.04891406]]

 [[-0.00098399]
  [ 0.03807291]
  [ 0.04891406]
  [ 0.0886287 ]]

 [[ 0.03807291]
  [ 0.04891406]
  [ 0.0886287 ]
  [ 0.10380903]]

 [[ 0.04891406]
  [ 0.0886287 ]
  [ 0.10380903]
  [ 0.1251049 ]]

 [[ 0.0886287 ]
  [ 0.10380903]
  [ 0.1251049 ]
  [ 0.09934011]]

 [[ 0.10380903]
  [ 0.1251049 ]
  [ 0.09934011]
  [ 0.08582541]]

 [[ 0.1251049 ]
  [ 0.09934011]
  [ 0.08582541]
  [ 0.10317119]]

 [[ 0.09934011]
  [ 0.08582541]
  [ 0.10317119]
  [ 0.12150924]]]


In [1187]:
X = X.reshape((X.shape[0], 2, 2, 1))
print (X)

[[[[-0.01221877]
   [-0.00939767]]

  [[-0.00098399]
   [ 0.03807291]]]


 [[[-0.00939767]
   [-0.00098399]]

  [[ 0.03807291]
   [ 0.04891406]]]


 [[[-0.00098399]
   [ 0.03807291]]

  [[ 0.04891406]
   [ 0.0886287 ]]]


 [[[ 0.03807291]
   [ 0.04891406]]

  [[ 0.0886287 ]
   [ 0.10380903]]]


 [[[ 0.04891406]
   [ 0.0886287 ]]

  [[ 0.10380903]
   [ 0.1251049 ]]]


 [[[ 0.0886287 ]
   [ 0.10380903]]

  [[ 0.1251049 ]
   [ 0.09934011]]]


 [[[ 0.10380903]
   [ 0.1251049 ]]

  [[ 0.09934011]
   [ 0.08582541]]]


 [[[ 0.1251049 ]
   [ 0.09934011]]

  [[ 0.08582541]
   [ 0.10317119]]]


 [[[ 0.09934011]
   [ 0.08582541]]

  [[ 0.10317119]
   [ 0.12150924]]]]


In [1196]:
# define model
model = Sequential()
model.add(TimeDistributed(Conv1D(filters=64, kernel_size=1, activation='relu'), input_shape=(None, 2, 1)))
model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=500, verbose=0)
# demonstrate prediction
x_input = data2.iloc[12:16,:].values
print (x_input)

[[0.1187402 ]
 [0.15382296]
 [0.14795534]
 [0.18394652]]


In [1197]:
x_input = x_input.reshape((1, 2, 2, 1))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[0.11118275]]


In [1198]:
# univariate convlstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import ConvLSTM2D
# choose a number of time steps
n_steps = 4
# split into samples
X,y = list(), list()
for i in range(len(training_set)):
    #find the end of this pattern
    end_ix = i + n_steps
    #check if we are beyond the sequence
    if end_ix > len(training_set) - 1:
        break
    #gather input and output parts of the pattern
    seq_x, seq_y = training_set[i:end_ix], training_set[end_ix]
    X.append(seq_x)
    y.append(seq_y)
X = np.array(X)
y = np.array(y)

In [1199]:
X = X.reshape((X.shape[0], 2, 1, 2, 1))

In [1200]:
# define model
model = Sequential()
model.add(ConvLSTM2D(filters=64, kernel_size=(1,2), activation='relu', input_shape=(2, 1, 2, 1)))
model.add(Flatten())
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [1201]:
# fit model
model.fit(X, y, epochs=500, verbose=0)

In [1206]:
# demonstrate prediction
x_input = data2.iloc[12:16,:].values
x_input = x_input.reshape((1, 2, 1, 2, 1))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[0.13049737]]
